version: '3.8'
services:
  postgres:
    restart: unless-stopped
    container_name: kelkun-notes-postgres
    image: postgis/postgis:16-3.4
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: ${POSTGRES_DB}
volumes:
  postgres: {}
